on:
  pull_request:
    types: [opened, reopened]

jobs:
  servicenow-integration:
    runs-on: ubuntu-latest
    env: 
      SNOW_URL: ${{ vars.SNOW_URL }}
      SNOW_USERNAME: ${{ secrets.SNOW_USERNAME }}
      SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@v4.2.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install axios
        run: npm install axios
      - name: Create Change Request
        uses: actions/github-script@v7
        with: 
          script: |
            const { createChangeRequest } = await import('.github/scripts/snow/snowRequests.js')
            await createChangeRequest()
      - name: Get change request from ServiceNow
        id: get-request
        env:
          sys_id: ${{ steps.create-request.outputs.sys_id }}
        uses: actions/github-script@v7
        with: 
          script: |
            const { waitForApproval)  = await import('.github/scripts/snow/snowRequests.js')
            await waitForApproval()

      - name: Update PR with Service Now 
        uses: actions/github-script@v7
        with:
          script: |
            github.pullRequests.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: 'ServiceNow Request: ${{ steps.get-request.outputs.state }}'
            })
